### ISSUE TITLE
Upgrade to BuildCraft 7

### ISSUE THREAD

**Issue by mrogaski** [AIE-Guild/AIE-Nomads-Modpack#35]
Upgrade to BC7 and update BCA to fix refinery supply.

**Comment by mrogaski** [comment]
First test failed, apparently on this iisue.

https://github.com/BuildCraft/BuildCraft/issues/2679

**Comment by StupidGenius** [comment]
Apparently, changing this http://github.com/AIE-Guild/AIE-Nomads-Modpack/blob/75145376b2b9c84970aaead559d87065fca00c7f/Overrides/config/forestry/modules.cfg#L78 to FALSE resolve this issue. (because we are using BuildCraft 7, not 6.)

Reference: https://github.com/BuildCraft/BuildCraft/issues/2679#issuecomment-97557908

**Comment by mrogaski** [comment]
There are a few other compatibility modules that need to be disabled, too.
